name: Build workflow

on:
  workflow_call:
    inputs:
      image_name:
        description: "Docker image name."
        required: true
        type: string
    outputs:
      image:
        description: "Docker image."
        value: ${{ jobs.config.outputs.image_tag }}

jobs:
  build:
    runs-on: [self-hosted]
    outputs:
      image: ${{ steps.build-image.outputs.image }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE: ${{ inputs.image_name }}
        run: |
          docker build -t $ECR_REGISTRY/$IMAGE .
          docker push $ECR_REGISTRY/$IMAGE
          echo "::set-output name=image::$ECR_REGISTRY/$IMAGE"
