name: CI workflow

on:
  workflow_call:
    inputs:
      image_name:
        description: "Docker image name."
        required: true
        type: string
      is_submodule:
        description: "Set submodule"
        default: false
        required: false
        type: boolean
      util_repository:
        description: "Util repository"
        required: false
        type: string
      util_path:
        description: "Path of utils"
        required: false
        type: string
      util_branch:
        description: "Brnach of utils"
        required: false
        type: string  
    outputs:
      image:
        description: "Docker image."
        value: ${{ jobs.config.outputs.image_tag }}

jobs:
  build:
    runs-on: [ubuntu-20.04]
    outputs:
      image: ${{ steps.build-image.outputs.image }}
    steps:
      - name: Clean Workspace
        uses: AutoModality/action-clean@v1.1.0

      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Checkout utils
        if: ${{ inputs.is_submodule }}
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.util_repository }}
          token: ${{ secrets.PAT }} # `GitHub_PAT` is a secret
          path: ${{ inputs.util_path }}
          ref: ${{ inputs.util_branch }}
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE: ${{ inputs.image_name }}
        run: |
          docker build -t $ECR_REGISTRY/$IMAGE .
          docker push $ECR_REGISTRY/$IMAGE
          echo "image=$ECR_REGISTRY/$IMAGE" >> $GITHUB_OUTPUT
